management:
  endpoint:
    health:
      show-details: always

    metrics:
      enabled: true

  endpoints:
    web:
      exposure:
        include:
          - configprops
          - health
          - info
          - prometheus


  info:
    git:
      mode: simple

  metrics:
    export:
      prometheus:
        enabled: true

server:
  tomcat:
    threads:
      max: 3

spring:
  application:
    name: keenetic-exporter

  cloud:
    openfeign:
      client:
        config:
          keenetic-rci:
            url: ${exporter.keenetic.client.url}
