management:
  endpoints:
    web:
      exposure:
        include:
          - configprops
          - health
          - info
          - prometheus

  info:
    git:
      mode: full

  metrics:
    export:
      prometheus:
        enabled: true

spring:
  cloud:
    openfeign:
      client:
        config:
          keenetic-rci:
            url: ${exporter.keenetic.client.url}
