management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  metrics:
    export:
      prometheus:
        enabled: true

spring:
  cloud:
    openfeign:
      client:
        config:
          keenetic-rci:
            url: ${exporter.keenetic.client.url}
